CREATE TABLE ECO_USER (
    ID SERIAL PRIMARY KEY,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Image TEXT,
    Date_Created TIMESTAMP NOT NULL
);

CREATE TABLE RECIPE (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    DishType VARCHAR(255) NOT NULL CHECK (DishType IN ('APPETIZER', 'SOUP', 'SALADS', 'MAIN_COURSE', 'SIDE_DISH', 'DESSERT', 'BEVERAGE', 'SNACK', 'BREAKFAST', 'BRUNCH', 'LUNCH', 'DINNER_SUPPER')),
    DietCategory VARCHAR(255) NOT NULL CHECK (DietCategory IN ('VEGETARIAN', 'VEGAN', 'PESCATARIAN', 'FLEXITARIAN', 'GLUTEN_FREE', 'LACTOSE_FREE', 'KETO', 'PALEO', 'MEDITERRANEAN', 'RAW_FOOD_DIET', 'PLANT_BASED')),
    Time INT NOT NULL,
    Summary TEXT NOT NULL,
    Image TEXT
);

CREATE TABLE INGREDIENT (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE REVIEW (
    ID SERIAL PRIMARY KEY,
    UserID INT NOT NULL,
    RecipeID INT NOT NULL,
    Rate INT,
    Content TEXT,
    Date_Created TIMESTAMP NOT NULL
);

CREATE TABLE RECIPE_INGREDIENT (
    ID SERIAL PRIMARY KEY,
    RecipeID INT NOT NULL,
    IngredientID INT NOT NULL,
    IngredientDetailID INT NOT NULL
);

CREATE TABLE INGREDIENT_DETAIL (
    ID SERIAL PRIMARY KEY,
    Quantity INT NOT NULL,
    Unit VARCHAR(30) NOT NULL
);

CREATE TABLE SHOPPING_ITEM (
    ID SERIAL PRIMARY KEY,
    IngredientID INT NOT NULL,
    RecipeID INT NOT NULL,
    UserID INT NOT NULL
);

CREATE TABLE SHOPPING_ITEM_DETAIL (
    ID SERIAL PRIMARY KEY,
    ShoppingItemID INT NOT NULL,
    Quantity INT NOT NULL,
    Unit VARCHAR(30) NOT NULL
);

CREATE TABLE RECIPE_STEP (
    ID SERIAL PRIMARY KEY,
    RecipeID INT NOT NULL,
    Number SMALLINT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Image TEXT
);