name: Deploy to EC2

on:
  workflow_call:
    # inputs:
    #   environment:
    #     required: false
    #     type: string
    #   trigger_pipeline:
    #     required: false
    #     type: string 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tf-outputs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ vars.ROLE_ARN }}
            role-session-name: github-actions-labsadm
            aws-region: ${{ vars.AWS_REGION }}

    #   - name: Setup AWS CLI
    #     uses: aws-actions/aws-cli-setup@v2

      - name: Load instance ID from file
        run: source tf-outputs.env

      - name: Deploy to EC2
        run: |
          aws ssm send-command --instance-ids $INSTANCE_ID --document-name "AWS-RunShellScript" --parameters commands=["docker-compose up -d"]