# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Chose environment to deploy"
        required: true
        type: choice
        options:
          - dev
          # - prod

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      with:
        gradle-version: '8.5'

    - name: Build with Gradle 8.5
      run: gradle build

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      id: semantic
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.ROLE_ARN }}
        role-session-name: github-actions-labsadm
        aws-region: ${{ vars.AWS_REGION }}

    # - name: Determine Docker Image Tag
    #   id: docker_tag
    #   run: |
    #     IMAGE_TAG="v0.0.0"
    #     if [ "${{ steps.semantic.outputs.new_release_published }}" = "true" ]; then
    #       echo "IMAGE_TAG=v${{ steps.semantic.outputs.new_release_version }}" | tee -a $GITHUB_ENV > variables.env
    #     else
    #       echo "IMAGE_TAG=$(git describe --tags --abbrev=0)" | tee -a $GITHUB_ENV > variables.env
    #     fi
    #     echo "IMAGE_TAG=$IMAGE_TAG"
    #     echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
    #   # run: |
    #   #   if [ "${{ steps.semantic.outputs.new_release_published }}" = "true" ]; then
    #   #     IMAGE_TAG="v${{ steps.semantic.outputs.new_release_version }}"
    #   #   else
    #   #     IMAGE_TAG=$(git describe --tags --abbrev=0)
    #   #   fi
    #   #   echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"
    - name: Check for existing tag
      id: check_tag
      run: |
        if git describe --tags --exact-match 2>/dev/null; then
          echo "::set-output name=tag_exists::true"
        else
          echo "::set-output name=tag_exists::false"
        fi

    - name: Check for new release
      id: check_release
      run: |
        if git describe --tags --abbrev=0 2>/dev/null; then
          echo "::set-output name=new_release::true"
        else
          echo "::set-output name=new_release::false"
        fi

    - name: Set image tag
      id: set_tag
      run: |
        if [[ "${{ steps.check_tag.outputs.tag_exists }}" == "true" ]]; then
          echo "Tag already exists, using existing tag"
          echo "::set-output name=image_tag::${{ github.ref }}"
        elif [[ "${{ steps.check_release.outputs.new_release }}" == "true" ]]; then
          echo "New release detected, setting image tag"
          echo "::set-output name=image_tag::${{ github.ref }}"
        else
          echo "No new release or existing tag, setting default image tag"
          echo "::set-output name=image_tag::0.0.0"
        fi

    - name: Use image tag
      run: |
        echo "Image tag: ${{ steps.set_tag.outputs.image_tag }}"
      
    - name: Login to Amazon ECR
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Build, tag, and push app-docker image to Amazon ECR Public
      env:
        IMAGE_TAG: ${{ steps.docker_tag.outputs.IMAGE_TAG}}
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: ${{ vars.ECR_ALIAS }}
        REPOSITORY: ${{ vars.ECR_NAME }}
        PREFIX: app
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$PREFIX-$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$PREFIX-$IMAGE_TAG

    - name: Build, tag, and push db-docker image to Amazon ECR Public
      env:
        IMAGE_TAG: ${{ steps.docker_tag.outputs.IMAGE_TAG}}
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: ${{ vars.ECR_ALIAS }}
        REPOSITORY: ${{ vars.ECR_NAME }}
        PREFIX: db
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$PREFIX-$IMAGE_TAG db
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$PREFIX-$IMAGE_TAG
        
  deliver:
    needs: build
    uses: marinaimeninnik/eco-bites-infra/.github/workflows/infra-create.yaml@back-deployment
    permissions:
      id-token: write
      contents: read
    with:
      environment: ${{ github.event.inputs.environment }}
      image_tag:  ${{ needs.build.outputs.IMAGE_TAG }}

